/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LocalOfficePreviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/fflate/esm/browser.js
var u8 = Uint8Array;
var u16 = Uint16Array;
var i32 = Int32Array;
var fleb = new u8([
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  4,
  4,
  4,
  4,
  5,
  5,
  5,
  5,
  0,
  /* unused */
  0,
  0,
  /* impossible */
  0
]);
var fdeb = new u8([
  0,
  0,
  0,
  0,
  1,
  1,
  2,
  2,
  3,
  3,
  4,
  4,
  5,
  5,
  6,
  6,
  7,
  7,
  8,
  8,
  9,
  9,
  10,
  10,
  11,
  11,
  12,
  12,
  13,
  13,
  /* unused */
  0,
  0
]);
var clim = new u8([16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15]);
var freb = function(eb, start) {
  var b = new u16(31);
  for (var i2 = 0; i2 < 31; ++i2) {
    b[i2] = start += 1 << eb[i2 - 1];
  }
  var r = new i32(b[30]);
  for (var i2 = 1; i2 < 30; ++i2) {
    for (var j = b[i2]; j < b[i2 + 1]; ++j) {
      r[j] = j - b[i2] << 5 | i2;
    }
  }
  return { b, r };
};
var _a = freb(fleb, 2);
var fl = _a.b;
var revfl = _a.r;
fl[28] = 258, revfl[258] = 28;
var _b = freb(fdeb, 0);
var fd = _b.b;
var revfd = _b.r;
var rev = new u16(32768);
for (i = 0; i < 32768; ++i) {
  x = (i & 43690) >> 1 | (i & 21845) << 1;
  x = (x & 52428) >> 2 | (x & 13107) << 2;
  x = (x & 61680) >> 4 | (x & 3855) << 4;
  rev[i] = ((x & 65280) >> 8 | (x & 255) << 8) >> 1;
}
var x;
var i;
var hMap = (function(cd, mb, r) {
  var s = cd.length;
  var i2 = 0;
  var l = new u16(mb);
  for (; i2 < s; ++i2) {
    if (cd[i2])
      ++l[cd[i2] - 1];
  }
  var le = new u16(mb);
  for (i2 = 1; i2 < mb; ++i2) {
    le[i2] = le[i2 - 1] + l[i2 - 1] << 1;
  }
  var co;
  if (r) {
    co = new u16(1 << mb);
    var rvb = 15 - mb;
    for (i2 = 0; i2 < s; ++i2) {
      if (cd[i2]) {
        var sv = i2 << 4 | cd[i2];
        var r_1 = mb - cd[i2];
        var v = le[cd[i2] - 1]++ << r_1;
        for (var m = v | (1 << r_1) - 1; v <= m; ++v) {
          co[rev[v] >> rvb] = sv;
        }
      }
    }
  } else {
    co = new u16(s);
    for (i2 = 0; i2 < s; ++i2) {
      if (cd[i2]) {
        co[i2] = rev[le[cd[i2] - 1]++] >> 15 - cd[i2];
      }
    }
  }
  return co;
});
var flt = new u8(288);
for (i = 0; i < 144; ++i)
  flt[i] = 8;
var i;
for (i = 144; i < 256; ++i)
  flt[i] = 9;
var i;
for (i = 256; i < 280; ++i)
  flt[i] = 7;
var i;
for (i = 280; i < 288; ++i)
  flt[i] = 8;
var i;
var fdt = new u8(32);
for (i = 0; i < 32; ++i)
  fdt[i] = 5;
var i;
var flrm = /* @__PURE__ */ hMap(flt, 9, 1);
var fdrm = /* @__PURE__ */ hMap(fdt, 5, 1);
var max = function(a) {
  var m = a[0];
  for (var i2 = 1; i2 < a.length; ++i2) {
    if (a[i2] > m)
      m = a[i2];
  }
  return m;
};
var bits = function(d, p, m) {
  var o = p / 8 | 0;
  return (d[o] | d[o + 1] << 8) >> (p & 7) & m;
};
var bits16 = function(d, p) {
  var o = p / 8 | 0;
  return (d[o] | d[o + 1] << 8 | d[o + 2] << 16) >> (p & 7);
};
var shft = function(p) {
  return (p + 7) / 8 | 0;
};
var slc = function(v, s, e) {
  if (s == null || s < 0)
    s = 0;
  if (e == null || e > v.length)
    e = v.length;
  return new u8(v.subarray(s, e));
};
var ec = [
  "unexpected EOF",
  "invalid block type",
  "invalid length/literal",
  "invalid distance",
  "stream finished",
  "no stream handler",
  ,
  // determined by compression function
  "no callback",
  "invalid UTF-8 data",
  "extra field too long",
  "date not in range 1980-2099",
  "filename too long",
  "stream finishing",
  "invalid zip data"
  // determined by unknown compression method
];
var err = function(ind, msg, nt) {
  var e = new Error(msg || ec[ind]);
  e.code = ind;
  if (Error.captureStackTrace)
    Error.captureStackTrace(e, err);
  if (!nt)
    throw e;
  return e;
};
var inflt = function(dat, st, buf, dict) {
  var sl = dat.length, dl = dict ? dict.length : 0;
  if (!sl || st.f && !st.l)
    return buf || new u8(0);
  var noBuf = !buf;
  var resize = noBuf || st.i != 2;
  var noSt = st.i;
  if (noBuf)
    buf = new u8(sl * 3);
  var cbuf = function(l2) {
    var bl = buf.length;
    if (l2 > bl) {
      var nbuf = new u8(Math.max(bl * 2, l2));
      nbuf.set(buf);
      buf = nbuf;
    }
  };
  var final = st.f || 0, pos = st.p || 0, bt = st.b || 0, lm = st.l, dm = st.d, lbt = st.m, dbt = st.n;
  var tbts = sl * 8;
  do {
    if (!lm) {
      final = bits(dat, pos, 1);
      var type = bits(dat, pos + 1, 3);
      pos += 3;
      if (!type) {
        var s = shft(pos) + 4, l = dat[s - 4] | dat[s - 3] << 8, t = s + l;
        if (t > sl) {
          if (noSt)
            err(0);
          break;
        }
        if (resize)
          cbuf(bt + l);
        buf.set(dat.subarray(s, t), bt);
        st.b = bt += l, st.p = pos = t * 8, st.f = final;
        continue;
      } else if (type == 1)
        lm = flrm, dm = fdrm, lbt = 9, dbt = 5;
      else if (type == 2) {
        var hLit = bits(dat, pos, 31) + 257, hcLen = bits(dat, pos + 10, 15) + 4;
        var tl = hLit + bits(dat, pos + 5, 31) + 1;
        pos += 14;
        var ldt = new u8(tl);
        var clt = new u8(19);
        for (var i2 = 0; i2 < hcLen; ++i2) {
          clt[clim[i2]] = bits(dat, pos + i2 * 3, 7);
        }
        pos += hcLen * 3;
        var clb = max(clt), clbmsk = (1 << clb) - 1;
        var clm = hMap(clt, clb, 1);
        for (var i2 = 0; i2 < tl; ) {
          var r = clm[bits(dat, pos, clbmsk)];
          pos += r & 15;
          var s = r >> 4;
          if (s < 16) {
            ldt[i2++] = s;
          } else {
            var c = 0, n = 0;
            if (s == 16)
              n = 3 + bits(dat, pos, 3), pos += 2, c = ldt[i2 - 1];
            else if (s == 17)
              n = 3 + bits(dat, pos, 7), pos += 3;
            else if (s == 18)
              n = 11 + bits(dat, pos, 127), pos += 7;
            while (n--)
              ldt[i2++] = c;
          }
        }
        var lt = ldt.subarray(0, hLit), dt = ldt.subarray(hLit);
        lbt = max(lt);
        dbt = max(dt);
        lm = hMap(lt, lbt, 1);
        dm = hMap(dt, dbt, 1);
      } else
        err(1);
      if (pos > tbts) {
        if (noSt)
          err(0);
        break;
      }
    }
    if (resize)
      cbuf(bt + 131072);
    var lms = (1 << lbt) - 1, dms = (1 << dbt) - 1;
    var lpos = pos;
    for (; ; lpos = pos) {
      var c = lm[bits16(dat, pos) & lms], sym = c >> 4;
      pos += c & 15;
      if (pos > tbts) {
        if (noSt)
          err(0);
        break;
      }
      if (!c)
        err(2);
      if (sym < 256)
        buf[bt++] = sym;
      else if (sym == 256) {
        lpos = pos, lm = null;
        break;
      } else {
        var add = sym - 254;
        if (sym > 264) {
          var i2 = sym - 257, b = fleb[i2];
          add = bits(dat, pos, (1 << b) - 1) + fl[i2];
          pos += b;
        }
        var d = dm[bits16(dat, pos) & dms], dsym = d >> 4;
        if (!d)
          err(3);
        pos += d & 15;
        var dt = fd[dsym];
        if (dsym > 3) {
          var b = fdeb[dsym];
          dt += bits16(dat, pos) & (1 << b) - 1, pos += b;
        }
        if (pos > tbts) {
          if (noSt)
            err(0);
          break;
        }
        if (resize)
          cbuf(bt + 131072);
        var end = bt + add;
        if (bt < dt) {
          var shift = dl - dt, dend = Math.min(dt, end);
          if (shift + bt < 0)
            err(3);
          for (; bt < dend; ++bt)
            buf[bt] = dict[shift + bt];
        }
        for (; bt < end; ++bt)
          buf[bt] = buf[bt - dt];
      }
    }
    st.l = lm, st.p = lpos, st.b = bt, st.f = final;
    if (lm)
      final = 1, st.m = lbt, st.d = dm, st.n = dbt;
  } while (!final);
  return bt != buf.length && noBuf ? slc(buf, 0, bt) : buf.subarray(0, bt);
};
var et = /* @__PURE__ */ new u8(0);
var b2 = function(d, b) {
  return d[b] | d[b + 1] << 8;
};
var b4 = function(d, b) {
  return (d[b] | d[b + 1] << 8 | d[b + 2] << 16 | d[b + 3] << 24) >>> 0;
};
var b8 = function(d, b) {
  return b4(d, b) + b4(d, b + 4) * 4294967296;
};
function inflateSync(data, opts) {
  return inflt(data, { i: 2 }, opts && opts.out, opts && opts.dictionary);
}
var td = typeof TextDecoder != "undefined" && /* @__PURE__ */ new TextDecoder();
var tds = 0;
try {
  td.decode(et, { stream: true });
  tds = 1;
} catch (e) {
}
var dutf8 = function(d) {
  for (var r = "", i2 = 0; ; ) {
    var c = d[i2++];
    var eb = (c > 127) + (c > 223) + (c > 239);
    if (i2 + eb > d.length)
      return { s: r, r: slc(d, i2 - 1) };
    if (!eb)
      r += String.fromCharCode(c);
    else if (eb == 3) {
      c = ((c & 15) << 18 | (d[i2++] & 63) << 12 | (d[i2++] & 63) << 6 | d[i2++] & 63) - 65536, r += String.fromCharCode(55296 | c >> 10, 56320 | c & 1023);
    } else if (eb & 1)
      r += String.fromCharCode((c & 31) << 6 | d[i2++] & 63);
    else
      r += String.fromCharCode((c & 15) << 12 | (d[i2++] & 63) << 6 | d[i2++] & 63);
  }
};
function strFromU8(dat, latin1) {
  if (latin1) {
    var r = "";
    for (var i2 = 0; i2 < dat.length; i2 += 16384)
      r += String.fromCharCode.apply(null, dat.subarray(i2, i2 + 16384));
    return r;
  } else if (td) {
    return td.decode(dat);
  } else {
    var _a2 = dutf8(dat), s = _a2.s, r = _a2.r;
    if (r.length)
      err(8);
    return s;
  }
}
var slzh = function(d, b) {
  return b + 30 + b2(d, b + 26) + b2(d, b + 28);
};
var zh = function(d, b, z) {
  var fnl = b2(d, b + 28), efl = b2(d, b + 30), fn = strFromU8(d.subarray(b + 46, b + 46 + fnl), !(b2(d, b + 8) & 2048)), es = b + 46 + fnl;
  var _a2 = z64hs(d, es, efl, z, b4(d, b + 20), b4(d, b + 24), b4(d, b + 42)), sc = _a2[0], su = _a2[1], off = _a2[2];
  return [b2(d, b + 10), sc, su, fn, es + efl + b2(d, b + 32), off];
};
var z64hs = function(d, b, l, z, sc, su, off) {
  var nsc = sc == 4294967295, nsu = su == 4294967295, noff = off == 4294967295, e = b + l;
  var nf = nsc + nsu + noff;
  if (z && nf) {
    for (; b + 4 < e; b += 4 + b2(d, b + 2)) {
      if (b2(d, b) == 1) {
        return [
          nsc ? b8(d, b + 4 + 8 * nsu) : sc,
          nsu ? b8(d, b + 4) : su,
          noff ? b8(d, b + 4 + 8 * (nsu + nsc)) : off,
          1
        ];
      }
    }
    if (z < 2)
      err(13);
  }
  return [sc, su, off, 0];
};
function unzipSync(data, opts) {
  var files = {};
  var e = data.length - 22;
  for (; b4(data, e) != 101010256; --e) {
    if (!e || data.length - e > 65558)
      err(13);
  }
  ;
  var c = b2(data, e + 8);
  if (!c)
    return {};
  var o = b4(data, e + 16);
  var z = b4(data, e - 20) == 117853008;
  if (z) {
    var ze = b4(data, e - 12);
    z = b4(data, ze) == 101075792;
    if (z) {
      c = b4(data, ze + 32);
      o = b4(data, ze + 48);
    }
  }
  var fltr = opts && opts.filter;
  for (var i2 = 0; i2 < c; ++i2) {
    var _a2 = zh(data, o, z), c_2 = _a2[0], sc = _a2[1], su = _a2[2], fn = _a2[3], no = _a2[4], off = _a2[5], b = slzh(data, off);
    o = no;
    if (!fltr || fltr({
      name: fn,
      size: sc,
      originalSize: su,
      compression: c_2
    })) {
      if (!c_2)
        files[fn] = slc(data, b, b + sc);
      else if (c_2 == 8)
        files[fn] = inflateSync(data.subarray(b, b + sc), { out: new u8(su) });
      else
        err(14, "unknown compression type " + c_2);
    }
  }
  return files;
}

// main.ts
var childProcess = __toESM(require("child_process"), 1);
var crypto = __toESM(require("crypto"), 1);
var fs = __toESM(require("fs"), 1);
var os = __toESM(require("os"), 1);
var path = __toESM(require("path"), 1);
var VIEW_TYPE = "local-office-preview-view";
var PLUGIN_ID = "local-office-preview";
var PPT_EXTENSIONS = ["ppt", "pptx", "pps", "ppsx"];
var EXCEL_EXTENSIONS = ["xls", "xlsx"];
var WORD_EXTENSIONS = ["doc", "docx"];
var FAST_WORD_EXTENSIONS = ["docx"];
var TEXT_EXTENSIONS = ["txt", "log"];
var ALL_EXTENSIONS = [
  ...PPT_EXTENSIONS,
  ...EXCEL_EXTENSIONS,
  ...WORD_EXTENSIONS,
  ...TEXT_EXTENSIONS
];
var DEFAULT_SETTINGS = {
  sofficePath: "",
  autoConvertOffice: true,
  maxExcelRows: 300,
  maxExcelColumns: 80
};
var LocalOfficePreviewPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.settings = normalizeSettings(await this.loadData());
    this.registerView(VIEW_TYPE, (leaf) => new LocalOfficePreviewView(leaf, this));
    this.registerFileExtensions();
    this.addSettingTab(new LocalOfficePreviewSettingTab(this.app, this));
    this.addCommand({
      id: "refresh-current-preview",
      name: "Refresh current preview",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(LocalOfficePreviewView);
        if (!view || !view.file) return false;
        if (checking) return true;
        void view.renderFilePreview(view.file, { forcePdf: true });
        return true;
      }
    });
    this.addCommand({
      id: "clear-temp-cache",
      name: "Clear temporary PDF cache",
      callback: () => {
        const cacheDir = this.getCacheDir();
        if (fs.existsSync(cacheDir)) {
          fs.rmSync(cacheDir, { recursive: true, force: true });
        }
        new import_obsidian.Notice("Local Office Preview cache cleared.");
      }
    });
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  registerFileExtensions() {
    for (const extension of ALL_EXTENSIONS) {
      try {
        this.registerExtensions([extension], VIEW_TYPE);
      } catch (error) {
        console.warn(
          `[${PLUGIN_ID}] Could not register .${extension}. It may already be handled by another plugin.`,
          error
        );
      }
    }
  }
  getVaultBasePath() {
    const adapter = this.app.vault.adapter;
    if (!adapter || typeof adapter.getBasePath !== "function") {
      throw new Error("Local Office Preview requires Obsidian desktop with a local filesystem vault.");
    }
    return adapter.getBasePath();
  }
  getFullPath(vaultPath) {
    const adapter = this.app.vault.adapter;
    if (adapter && typeof adapter.getFullPath === "function") {
      return adapter.getFullPath(vaultPath);
    }
    return path.join(this.getVaultBasePath(), vaultPath);
  }
  getCacheDir() {
    const vaultKey = crypto.createHash("sha1").update(this.getVaultBasePath()).digest("hex");
    return path.join(os.tmpdir(), PLUGIN_ID, vaultKey);
  }
  getPdfCachePath(file) {
    const sourcePath = this.getFullPath(file.path);
    const sourceStat = fs.statSync(sourcePath);
    const cacheKey = crypto.createHash("sha1").update(`${sourcePath}:${sourceStat.mtimeMs}:${sourceStat.size}`).digest("hex");
    return path.join(this.getCacheDir(), `${cacheKey}.pdf`);
  }
  hasPdfCache(file) {
    return fs.existsSync(this.getPdfCachePath(file));
  }
  findSoffice() {
    const configured = this.settings.sofficePath ? [this.settings.sofficePath] : [];
    const candidates = [
      ...configured,
      "soffice",
      "libreoffice",
      "C:\\Program Files\\LibreOffice\\program\\soffice.exe",
      "C:\\Program Files (x86)\\LibreOffice\\program\\soffice.exe",
      "/Applications/LibreOffice.app/Contents/MacOS/soffice",
      "/usr/bin/soffice",
      "/usr/local/bin/soffice",
      "/snap/bin/libreoffice"
    ];
    for (const candidate of unique(candidates.filter(Boolean))) {
      if (candidate === "soffice" || candidate === "libreoffice") return candidate;
      if (fs.existsSync(candidate)) return candidate;
    }
    return this.settings.sofficePath || "soffice";
  }
  async convertOfficeToPdf(file, force) {
    const sourcePath = this.getFullPath(file.path);
    const sourceStat = fs.statSync(sourcePath);
    const extension = path.extname(sourcePath);
    const cacheKey = crypto.createHash("sha1").update(`${sourcePath}:${sourceStat.mtimeMs}:${sourceStat.size}`).digest("hex");
    const cacheDir = this.getCacheDir();
    const workDir = path.join(cacheDir, "work", cacheKey);
    const pdfPath = this.getPdfCachePath(file);
    if (!force && fs.existsSync(pdfPath)) {
      return pdfPath;
    }
    fs.mkdirSync(workDir, { recursive: true });
    fs.mkdirSync(cacheDir, { recursive: true });
    const tempInput = path.join(workDir, `input${extension}`);
    fs.copyFileSync(sourcePath, tempInput);
    const errors = [];
    try {
      await this.convertWithLibreOffice(tempInput, workDir);
      const convertedPdf = path.join(workDir, "input.pdf");
      if (!fs.existsSync(convertedPdf)) {
        throw new Error("LibreOffice finished without producing a PDF.");
      }
      fs.copyFileSync(convertedPdf, pdfPath);
      return pdfPath;
    } catch (error) {
      errors.push(`LibreOffice: ${getErrorMessage(error)}`);
    }
    if (process.platform === "win32") {
      try {
        await this.convertWithDesktopOffice(tempInput, pdfPath);
        if (!fs.existsSync(pdfPath)) {
          throw new Error("Desktop Office finished without producing a PDF.");
        }
        return pdfPath;
      } catch (error) {
        errors.push(`Desktop Office/WPS: ${getErrorMessage(error)}`);
      }
    }
    throw new Error(
      [
        "Could not create a PDF preview.",
        "Install LibreOffice, set the soffice.exe path in plugin settings, or use WPS/Microsoft Office on Windows.",
        ...errors
      ].join("\n")
    );
  }
  async convertWithLibreOffice(inputPath, outputDir) {
    await execFilePromise(this.findSoffice(), [
      "--headless",
      "--nologo",
      "--nodefault",
      "--nofirststartwizard",
      "--convert-to",
      "pdf",
      "--outdir",
      outputDir,
      inputPath
    ]);
  }
  async convertWithDesktopOffice(inputPath, outputPath) {
    const extension = path.extname(inputPath).toLowerCase();
    const script = getDesktopOfficeExportScript(inputPath, outputPath, extension);
    await execFilePromise("powershell.exe", [
      "-NoProfile",
      "-ExecutionPolicy",
      "Bypass",
      "-Command",
      script
    ]);
  }
};
var LocalOfficePreviewView = class extends import_obsidian.FileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.file = null;
    this.workbook = null;
    this.selectedSheet = "";
    this.pdfObjectUrl = null;
    this.pdfRenderToken = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "Local Office Preview";
  }
  async onOpen() {
    await super.onOpen();
    window.setTimeout(() => {
      if (!this.file) return;
      const extension = this.file.extension.toLowerCase();
      if (!PPT_EXTENSIONS.includes(extension) && !extension.includes("xls") && extension !== "doc") return;
      void this.renderFilePreview(this.file, { forcePdf: false });
    }, 150);
  }
  async onLoadFile(file) {
    await super.onLoadFile(file);
    this.file = file;
    this.workbook = null;
    this.selectedSheet = "";
    await this.renderFilePreview(file, { forcePdf: false });
  }
  async onUnloadFile(file) {
    await super.onUnloadFile(file);
    this.pdfRenderToken += 1;
    this.revokePdfObjectUrl();
    this.file = null;
    this.workbook = null;
    this.selectedSheet = "";
    this.contentEl.empty();
    this.contentEl.removeClass("lop-view");
  }
  async onClose() {
    await super.onClose();
    this.pdfRenderToken += 1;
    this.revokePdfObjectUrl();
    this.contentEl.empty();
    this.contentEl.removeClass("lop-view");
  }
  async renderFilePreview(file, options) {
    this.pdfRenderToken += 1;
    this.revokePdfObjectUrl();
    this.file = file;
    this.contentEl.empty();
    this.contentEl.removeClass("lop-view");
    const root = this.contentEl.createDiv({ cls: "lop-view" });
    const toolbar = root.createDiv({ cls: "lop-toolbar" });
    const body = root.createDiv({ cls: "lop-body" });
    const status = toolbar.createDiv({ cls: "lop-status", text: file.path });
    const copyButton = toolbar.createEl("button", { text: "Copy Text" });
    copyButton.addEventListener("click", () => {
      void this.copyFileText(file, copyButton, status);
    });
    const extension = file.extension.toLowerCase();
    if (TEXT_EXTENSIONS.includes(extension)) {
      await this.renderText(file, body, status);
      return;
    }
    if (EXCEL_EXTENSIONS.includes(extension)) {
      await this.renderExcel(file, toolbar, body, status, extension);
      return;
    }
    if (FAST_WORD_EXTENSIONS.includes(extension)) {
      await this.renderDocx(file, body, status);
      return;
    }
    if (PPT_EXTENSIONS.includes(extension) || WORD_EXTENSIONS.includes(extension)) {
      const refreshButton = toolbar.createEl("button", { text: "Refresh PDF" });
      refreshButton.addEventListener("click", () => {
        void this.renderPdf(file, body, status, true);
      });
      this.schedulePdfRender(file, body, status, options.forcePdf);
      return;
    }
    body.createDiv({ cls: "lop-error", text: `Unsupported file type: ${extension}` });
  }
  async renderText(file, body, status) {
    body.empty();
    try {
      const text = await this.app.vault.read(file);
      body.createEl("pre", { cls: "lop-text", text });
      status.setText(`Text preview: ${file.path}`);
    } catch (error) {
      this.renderError(body, status, error);
    }
  }
  async copyFileText(file, button, status) {
    const originalText = button.textContent || "Copy Text";
    button.textContent = "Copying...";
    button.disabled = true;
    try {
      const text = await this.extractCopyText(file);
      if (!text.trim()) {
        new import_obsidian.Notice("No copyable text found.");
        return;
      }
      await navigator.clipboard.writeText(text);
      new import_obsidian.Notice("Copied preview text.");
      status.setText(`Copied text: ${file.path}`);
    } catch (error) {
      const message = getErrorMessage(error);
      new import_obsidian.Notice(message);
      status.setText(`Copy failed: ${message}`);
    } finally {
      button.textContent = originalText;
      button.disabled = false;
    }
  }
  async extractCopyText(file) {
    var _a2;
    const extension = file.extension.toLowerCase();
    if (TEXT_EXTENSIONS.includes(extension)) {
      return this.app.vault.read(file);
    }
    if (extension === "xlsx") {
      const workbook = this.workbook || parseXlsxFast(new Uint8Array(await this.app.vault.readBinary(file)));
      const sheetName = this.selectedSheet || ((_a2 = workbook.sheets[0]) == null ? void 0 : _a2.name) || "";
      return workbookToText(workbook, sheetName);
    }
    if (extension === "docx") {
      return extractDocxText(new Uint8Array(await this.app.vault.readBinary(file)));
    }
    if (extension === "pptx" || extension === "ppsx") {
      return extractPptxText(new Uint8Array(await this.app.vault.readBinary(file)));
    }
    throw new Error("Copy Text currently supports TXT, LOG, XLSX, DOCX, PPTX, and PPSX. Legacy DOC/XLS/PPT can still be copied from the PDF viewer when text selection is available.");
  }
  async renderExcel(file, toolbar, body, status, extension) {
    var _a2;
    const pdfButton = toolbar.createEl("button", { text: "PDF Preview" });
    pdfButton.addEventListener("click", () => {
      void this.renderPdf(file, body, status, false);
    });
    if (extension === "xls") {
      this.schedulePdfRender(file, body, status, false);
      return;
    }
    body.empty();
    body.createDiv({ cls: "lop-empty", text: "Loading workbook..." });
    status.setText(`Excel fast preview: ${file.path}`);
    try {
      if (!this.workbook) {
        const buffer = await this.app.vault.readBinary(file);
        this.workbook = parseXlsxFast(new Uint8Array(buffer));
        this.selectedSheet = ((_a2 = this.workbook.sheets[0]) == null ? void 0 : _a2.name) || "";
      }
      const sheetSelect = toolbar.createEl("select");
      for (const sheetName of this.workbook.sheets.map((sheet) => sheet.name)) {
        sheetSelect.createEl("option", {
          text: sheetName,
          value: sheetName
        });
      }
      sheetSelect.value = this.selectedSheet;
      sheetSelect.addEventListener("change", () => {
        this.selectedSheet = sheetSelect.value;
        this.renderExcelSheet(body, status);
      });
      this.renderExcelSheet(body, status);
    } catch (error) {
      this.renderError(body, status, error);
    }
  }
  renderExcelSheet(body, status) {
    var _a2, _b2;
    body.empty();
    if (!this.workbook || !this.selectedSheet) {
      body.createDiv({ cls: "lop-empty", text: "This workbook has no visible sheets." });
      return;
    }
    const sheet = this.workbook.sheets.find((candidate) => candidate.name === this.selectedSheet);
    if (!sheet) {
      body.createDiv({ cls: "lop-empty", text: "Selected sheet could not be found." });
      return;
    }
    const maxRows = Math.max(1, this.plugin.settings.maxExcelRows);
    const maxColumns = Math.max(1, this.plugin.settings.maxExcelColumns);
    const rowCount = sheet.rows.length;
    const columnCount = Math.min(maxColumns, getMaxColumnCount(sheet.rows));
    const visibleRowCount = Math.min(maxRows, rowCount);
    body.createDiv({
      cls: "lop-sheet-info",
      text: `${this.selectedSheet} \xB7 showing ${visibleRowCount}/${rowCount} rows \xB7 ${columnCount} columns`
    });
    const tableWrap = body.createDiv({ cls: "lop-table-wrap" });
    const table = tableWrap.createEl("table", { cls: "lop-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "#" });
    for (let columnIndex = 0; columnIndex < columnCount; columnIndex += 1) {
      headerRow.createEl("th", { text: columnLabel(columnIndex) });
    }
    const tbody = table.createEl("tbody");
    for (let rowIndex = 1; rowIndex <= visibleRowCount; rowIndex += 1) {
      const row = sheet.rows[rowIndex - 1] || [];
      const tr = tbody.createEl("tr");
      tr.createEl("th", { text: String(rowIndex) });
      for (let columnIndex = 1; columnIndex <= columnCount; columnIndex += 1) {
        tr.createEl("td", { text: row[columnIndex - 1] || "" });
      }
    }
    status.setText(`Excel fast preview: ${(_b2 = (_a2 = this.file) == null ? void 0 : _a2.path) != null ? _b2 : ""}`);
  }
  async renderDocx(file, body, status) {
    body.empty();
    body.createDiv({ cls: "lop-empty", text: "Loading DOCX preview..." });
    status.setText(`DOCX text preview: ${file.path}`);
    try {
      const text = extractDocxText(new Uint8Array(await this.app.vault.readBinary(file)));
      body.empty();
      body.createEl("pre", {
        cls: "lop-text lop-docx-text",
        text: text || "(No extractable text found.)"
      });
      status.setText(`DOCX text preview: ${file.path}`);
    } catch (error) {
      body.empty();
      this.renderError(body, status, error);
    }
  }
  schedulePdfRender(file, body, status, force) {
    const token = ++this.pdfRenderToken;
    const filePath = file.path;
    body.empty();
    const hasCache = !force && this.plugin.hasPdfCache(file);
    body.createDiv({
      cls: "lop-empty",
      text: hasCache ? "Loading cached PDF preview..." : "Converting locally to PDF..."
    });
    status.setText(hasCache ? `Loading cached PDF: ${file.path}` : `Converting: ${file.path}`);
    const run = () => {
      if (this.pdfRenderToken !== token) return;
      if (!this.file || this.file.path !== filePath) return;
      void this.renderPdf(file, body, status, force);
    };
    window.setTimeout(run, 100);
  }
  async renderPdf(file, body, status, force) {
    body.empty();
    const hasCache = !force && this.plugin.hasPdfCache(file);
    body.createDiv({
      cls: "lop-empty",
      text: hasCache ? "Loading cached PDF preview..." : "Converting locally to PDF..."
    });
    status.setText(hasCache ? `Loading cached PDF: ${file.path}` : `Converting: ${file.path}`);
    try {
      const pdfPath = await this.plugin.convertOfficeToPdf(file, force);
      const pdfUrl = this.createPdfObjectUrl(pdfPath);
      body.empty();
      const iframe = body.createEl("iframe", {
        cls: "lop-pdf",
        attr: {
          src: pdfUrl
        }
      });
      iframe.setAttr("title", `${file.basename}.pdf`);
      status.setText(`PDF preview: ${path.basename(pdfPath)}`);
    } catch (error) {
      body.empty();
      this.renderError(body, status, error);
    }
  }
  createPdfObjectUrl(pdfPath) {
    this.revokePdfObjectUrl();
    const bytes = fs.readFileSync(pdfPath);
    const arrayBuffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
    const blob = new Blob([arrayBuffer], { type: "application/pdf" });
    this.pdfObjectUrl = URL.createObjectURL(blob);
    return this.pdfObjectUrl;
  }
  revokePdfObjectUrl() {
    if (this.pdfObjectUrl) {
      URL.revokeObjectURL(this.pdfObjectUrl);
      this.pdfObjectUrl = null;
    }
  }
  renderError(body, status, error) {
    const message = error instanceof Error ? error.message : String(error);
    status.setText("Preview failed");
    const container = body.createDiv({ cls: "lop-error" });
    container.createDiv({ text: "Preview failed." });
    container.createEl("p", { text: message });
    container.createEl("p", {
      text: "For PPT, Word, legacy .xls, and Excel PDF preview, install LibreOffice, set the full soffice.exe path in plugin settings, or use WPS/Microsoft Office on Windows."
    });
    container.createEl("code", {
      text: "C:\\Program Files\\LibreOffice\\program\\soffice.exe"
    });
  }
};
var LocalOfficePreviewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("LibreOffice soffice path").setDesc("Leave empty to auto-detect. Set the full path if PDF conversion fails.").addText(
      (text) => text.setPlaceholder("C:\\Program Files\\LibreOffice\\program\\soffice.exe").setValue(this.plugin.settings.sofficePath).onChange(async (value) => {
        this.plugin.settings.sofficePath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Excel fast preview row limit").setDesc("Limits rows rendered in Obsidian for performance.").addText(
      (text) => text.setPlaceholder("300").setValue(String(this.plugin.settings.maxExcelRows)).onChange(async (value) => {
        this.plugin.settings.maxExcelRows = parsePositiveInteger(value, DEFAULT_SETTINGS.maxExcelRows);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Excel fast preview column limit").setDesc("Limits columns rendered in Obsidian for performance.").addText(
      (text) => text.setPlaceholder("80").setValue(String(this.plugin.settings.maxExcelColumns)).onChange(async (value) => {
        this.plugin.settings.maxExcelColumns = parsePositiveInteger(value, DEFAULT_SETTINGS.maxExcelColumns);
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("p", {
      text: "The plugin is read-only, does not make network requests, and stores PDF previews in the system temp directory instead of your vault."
    });
  }
};
function execFilePromise(command, args) {
  return new Promise((resolve, reject) => {
    childProcess.execFile(
      command,
      args,
      { windowsHide: true, timeout: 12e4 },
      (error, stdout, stderr) => {
        if (error) {
          const detail = [error.message, stdout, stderr].filter(Boolean).join("\n");
          reject(new Error(detail));
          return;
        }
        resolve();
      }
    );
  });
}
function getDesktopOfficeExportScript(inputPath, outputPath, extension) {
  const input = toPowerShellString(inputPath);
  const output = toPowerShellString(outputPath);
  const createComHelper = `
function New-FirstComObject([string[]]$progIds) {
  $errors = @()
  foreach ($progId in $progIds) {
    try {
      return New-Object -ComObject $progId
    } catch {
      $errors += "$($progId): $($_.Exception.Message)"
    }
  }
  throw "No supported Office/WPS COM application could be created. $($errors -join '; ')"
}
`;
  if (PPT_EXTENSIONS.includes(extension.replace(".", ""))) {
    return `
$ErrorActionPreference = 'Stop'
${createComHelper}
$inputPath = ${input}
$outputPath = ${output}
$app = $null
$presentation = $null
try {
  $app = New-FirstComObject @('Kwpp.Application', 'PowerPoint.Application')
  $presentation = $app.Presentations.Open($inputPath, $true, $true, $false)
  $presentation.SaveAs($outputPath, 32)
} finally {
  if ($presentation -ne $null) { $presentation.Close() | Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($presentation) | Out-Null }
  if ($app -ne $null) { $app.Quit() | Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($app) | Out-Null }
}
`;
  }
  if (EXCEL_EXTENSIONS.includes(extension.replace(".", ""))) {
    return `
$ErrorActionPreference = 'Stop'
${createComHelper}
$inputPath = ${input}
$outputPath = ${output}
$app = $null
$workbook = $null
try {
  $app = New-FirstComObject @('Ket.Application', 'Excel.Application')
  $app.DisplayAlerts = $false
  $workbook = $app.Workbooks.Open($inputPath, 3, $true)
  $workbook.ExportAsFixedFormat(0, $outputPath)
} finally {
  if ($workbook -ne $null) { $workbook.Close($false) | Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($workbook) | Out-Null }
  if ($app -ne $null) { $app.Quit() | Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($app) | Out-Null }
}
`;
  }
  if (WORD_EXTENSIONS.includes(extension.replace(".", ""))) {
    return `
$ErrorActionPreference = 'Stop'
${createComHelper}
$inputPath = ${input}
$outputPath = ${output}
$app = $null
$document = $null
try {
  $app = New-FirstComObject @('Kwps.Application', 'Word.Application')
  $app.Visible = $false
  $document = $app.Documents.Open($inputPath, $false, $true)
  $document.ExportAsFixedFormat($outputPath, 17)
} finally {
  if ($document -ne $null) { $document.Close($false) | Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($document) | Out-Null }
  if ($app -ne $null) { $app.Quit() | Out-Null; [System.Runtime.InteropServices.Marshal]::ReleaseComObject($app) | Out-Null }
}
`;
  }
  throw new Error(`Desktop Office PDF export does not support ${extension}.`);
}
function toPowerShellString(value) {
  return `'${value.replace(/'/g, "''")}'`;
}
function getErrorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}
function unique(items) {
  return [...new Set(items)];
}
function parseXlsxFast(bytes) {
  const zip = unzipSync(bytes);
  const workbookXml = readZipText(zip, "xl/workbook.xml");
  const workbookRelsXml = readZipText(zip, "xl/_rels/workbook.xml.rels");
  const sharedStrings = readSharedStrings(zip);
  const sheetRefs = readWorkbookSheets(workbookXml);
  const relationships = readWorkbookRelationships(workbookRelsXml);
  const sheets = sheetRefs.map((sheetRef) => {
    const target = relationships.get(sheetRef.relationshipId);
    const normalizedTarget = target ? normalizeSheetTarget(target) : "";
    const rows = normalizedTarget && zip[normalizedTarget] ? readWorksheetRows(readZipText(zip, normalizedTarget), sharedStrings) : [];
    return {
      name: sheetRef.name,
      rows
    };
  });
  return { sheets };
}
function readSharedStrings(zip) {
  const entry = zip["xl/sharedStrings.xml"];
  if (!entry) return [];
  const doc = parseXml(strFromU8(entry));
  return Array.from(doc.getElementsByTagName("si")).map((item) => item.textContent || "");
}
function readWorkbookSheets(xml) {
  const doc = parseXml(xml);
  return Array.from(doc.getElementsByTagName("sheet")).map((sheet) => ({
    name: sheet.getAttribute("name") || "Sheet",
    relationshipId: sheet.getAttribute("r:id") || ""
  }));
}
function readWorkbookRelationships(xml) {
  const doc = parseXml(xml);
  const relationships = /* @__PURE__ */ new Map();
  for (const relationship of Array.from(doc.getElementsByTagName("Relationship"))) {
    const id = relationship.getAttribute("Id");
    const target = relationship.getAttribute("Target");
    if (id && target) relationships.set(id, target);
  }
  return relationships;
}
function readWorksheetRows(xml, sharedStrings) {
  const doc = parseXml(xml);
  const rows = [];
  for (const rowEl of Array.from(doc.getElementsByTagName("row"))) {
    const rowNumber = Number.parseInt(rowEl.getAttribute("r") || "", 10);
    const rowIndex = Number.isFinite(rowNumber) ? rowNumber - 1 : rows.length;
    const row = rows[rowIndex] || [];
    for (const cellEl of Array.from(rowEl.getElementsByTagName("c"))) {
      const ref = cellEl.getAttribute("r") || "";
      const columnIndex = cellRefToColumnIndex(ref);
      if (columnIndex < 0) continue;
      row[columnIndex] = readCellValue(cellEl, sharedStrings);
    }
    rows[rowIndex] = row;
  }
  return rows;
}
function workbookToText(workbook, selectedSheet) {
  const sheet = workbook.sheets.find((candidate) => candidate.name === selectedSheet) || workbook.sheets[0];
  if (!sheet) return "";
  const lines = [`[${sheet.name}]`];
  for (const row of sheet.rows) {
    lines.push(row.map(cleanCellForCopy).join("	"));
  }
  return lines.join("\n");
}
function extractDocxText(bytes) {
  const zip = unzipSync(bytes);
  const docEntries = Object.keys(zip).filter(
    (key) => key === "word/document.xml" || /^word\/header\d+\.xml$/.test(key) || /^word\/footer\d+\.xml$/.test(key)
  ).sort((a, b) => {
    if (a === "word/document.xml") return -1;
    if (b === "word/document.xml") return 1;
    return a.localeCompare(b);
  });
  const sections = [];
  for (const entry of docEntries) {
    sections.push(extractParagraphText(readZipText(zip, entry), "w:p", "w:t"));
  }
  return sections.filter(Boolean).join("\n\n");
}
function extractPptxText(bytes) {
  const zip = unzipSync(bytes);
  const slideEntries = Object.keys(zip).filter((key) => /^ppt\/slides\/slide\d+\.xml$/.test(key)).sort((a, b) => getSlideNumber(a) - getSlideNumber(b));
  const slides = [];
  for (const entry of slideEntries) {
    const slideText = extractParagraphText(readZipText(zip, entry), "a:p", "a:t");
    if (slideText.trim()) {
      slides.push(`Slide ${getSlideNumber(entry)}
${slideText}`);
    }
  }
  return slides.join("\n\n");
}
function extractParagraphText(xml, paragraphTag, textTag) {
  const doc = parseXml(xml);
  const paragraphs = Array.from(doc.getElementsByTagName(paragraphTag));
  const lines = [];
  for (const paragraph of paragraphs) {
    const text = Array.from(paragraph.getElementsByTagName(textTag)).map((node) => node.textContent || "").join("");
    if (text.trim()) lines.push(text);
  }
  return lines.join("\n");
}
function getSlideNumber(pathValue) {
  const match = pathValue.match(/slide(\d+)\.xml$/);
  return match ? Number.parseInt(match[1], 10) : 0;
}
function cleanCellForCopy(value) {
  return value.replace(/\r?\n/g, " ").replace(/\t/g, " ").trim();
}
function readCellValue(cellEl, sharedStrings) {
  var _a2;
  const type = cellEl.getAttribute("t");
  if (type === "inlineStr") {
    const inlineString = cellEl.getElementsByTagName("is")[0];
    return (inlineString == null ? void 0 : inlineString.textContent) || "";
  }
  const value = ((_a2 = cellEl.getElementsByTagName("v")[0]) == null ? void 0 : _a2.textContent) || "";
  if (type === "s") {
    const sharedStringIndex = Number.parseInt(value, 10);
    return sharedStrings[sharedStringIndex] || "";
  }
  if (type === "b") return value === "1" ? "TRUE" : "FALSE";
  return value;
}
function readZipText(zip, key) {
  const entry = zip[key];
  if (!entry) throw new Error(`Missing XLSX entry: ${key}`);
  return strFromU8(entry);
}
function parseXml(xml) {
  return new DOMParser().parseFromString(xml, "application/xml");
}
function normalizeSheetTarget(target) {
  const normalized = target.replace(/\\/g, "/").replace(/^\/+/, "");
  if (normalized.startsWith("xl/")) return normalized;
  return `xl/${normalized}`;
}
function cellRefToColumnIndex(ref) {
  const letters = (ref.match(/^[A-Z]+/i) || [""])[0].toUpperCase();
  if (!letters) return -1;
  let index = 0;
  for (const letter of letters) {
    index = index * 26 + (letter.charCodeAt(0) - 64);
  }
  return index - 1;
}
function getMaxColumnCount(rows) {
  return rows.reduce((max2, row) => Math.max(max2, row.length), 0);
}
function columnLabel(index) {
  let label = "";
  let current = index + 1;
  while (current > 0) {
    const remainder = (current - 1) % 26;
    label = String.fromCharCode(65 + remainder) + label;
    current = Math.floor((current - 1) / 26);
  }
  return label;
}
function normalizeSettings(value) {
  const source = isRecord(value) ? value : {};
  return {
    sofficePath: typeof source.sofficePath === "string" ? source.sofficePath : DEFAULT_SETTINGS.sofficePath,
    autoConvertOffice: typeof source.autoConvertOffice === "boolean" ? source.autoConvertOffice : DEFAULT_SETTINGS.autoConvertOffice,
    maxExcelRows: parsePositiveIntegerValue(source.maxExcelRows, DEFAULT_SETTINGS.maxExcelRows),
    maxExcelColumns: parsePositiveIntegerValue(source.maxExcelColumns, DEFAULT_SETTINGS.maxExcelColumns)
  };
}
function isRecord(value) {
  return typeof value === "object" && value !== null;
}
function parsePositiveIntegerValue(value, fallback) {
  if (typeof value === "number" && Number.isFinite(value) && value >= 1) {
    return Math.floor(value);
  }
  if (typeof value === "string") {
    return parsePositiveInteger(value, fallback);
  }
  return fallback;
}
function parsePositiveInteger(value, fallback) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed < 1) return fallback;
  return parsed;
}

/* nosourcemap */